# Generated by Django 4.1.1 on 2022-09-07 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=200)),
                ('profile_pic', models.ImageField(null=True, upload_to='profilepics')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('min_GPA', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('bio', models.TextField(max_length=200)),
                ('GPA', models.FloatField()),
                ('hometown', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('profile_pic', models.ImageField(null=True, upload_to='profilepics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_id', to='coachescornerapi.coach')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruit', to='coachescornerapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='Open_spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('applicants', models.ManyToManyField(related_name='applicant_player', through='coachescornerapi.Applicant', to='coachescornerapi.player')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachescornerapi.college')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachescornerapi.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(max_length=100)),
                ('attendees', models.ManyToManyField(related_name='attending', through='coachescornerapi.Attendee', to='coachescornerapi.coach')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachescornerapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='coachescornerapi.college')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_id', to='coachescornerapi.player')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachescornerapi.college'),
        ),
        migrations.AddField(
            model_name='coach',
            name='recruits',
            field=models.ManyToManyField(related_name='recruits', through='coachescornerapi.Recruit', to='coachescornerapi.player'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendee',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachescornerapi.coach'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachescornerapi.game'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='open_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_spot_id', to='coachescornerapi.open_spot'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='coachescornerapi.player'),
        ),
    ]
