# Generated by Django 4.1.1 on 2022-09-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachescornerapi', '0002_rename_location_college_city_college_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
