# Generated by Django 4.1.1 on 2022-09-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachescornerapi', '0003_rename_location_game_city_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coachescornerapi.college'),
        ),
    ]
