# Generated by Django 4.1.1 on 2022-09-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachescornerapi', '0004_alter_coach_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='grade',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
