# Generated by Django 4.1.1 on 2022-09-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coachescornerapi', '0005_player_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='profile_pic',
        ),
    ]
